[package]
name = "easyhttpmock-vetis-tokio"
version = "0.1.1"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "EasyHttpMock adapter for Vetis HTTP server using tokio runtime."
readme = "README.md"
license.workspace = true
keywords = ["http", "mock", "testing"]
publish = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = [
  "http1",
  "http2",
  #"http3"
]

xml = ["easyhttpmock/xml"]
json = ["easyhttpmock/json"]
http1 = ["vetis-tokio/http1"]
http2 = ["vetis-tokio/http2"]
http3 = ["vetis-tokio/http3"]

rust-tls = ["vetis-tokio/rust-tls"]

[dependencies]
caramelo = { workspace = true }
easyhttpmock = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
rand = { workspace = true, default-features = false }
tokio = { version = "1.53.1", default-features = false }
vetis-tokio = { version = "0.1.1", features = [
  "http1",
  "http2",
  #"http3",
  "rust-tls",
], default-features = false }

[dev-dependencies]
deboa = { workspace = true }
deboa-tokio = { version = "0.1.0", default-features = false, features = [
  "http1",
  "http2",
  #"http3",
  "rust-tls",
  "default-rustls-provider",
  "default-rustls-verifier",
] }
tokio = { version = "1.50.0", default-features = false, features = ["macros"] }
